<?php

namespace Blog\BlogBundle\Repository;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
//use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
//use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
//use Symfony\Component\HttpFoundation\Response;
//use Symfony\Component\HttpFoundation\Request;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function getIdArrayByName($name)
	{
		//return $this->getEntityManager()
		//					->createQuery("SELECT p.id FROM BlogBlogBundle:Post p
		//										WHERE p.title LIKE :name")
		//					->setParameter('name', '%' . $name . '%')
		//					->getResult();

		$repository = $this->getDoctrine()
    			->getRepository('BlogBlogBundle:Post');

    	$query = $repository->createQueryBuilder('p')
    			->where('p.title IN (:ids)')
    			->setParameter('ids', $name)
    			->getQuery();
    			//->where('p.id IN (:ids)')
    			//->setParameter('ids', $result)

    	$post = $query->getIdResult();

    	return $post;
	}
}
